[General]

[Rule]
FINAL,DIRECT

[Header Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) header-replace-regex 110907 110907 110905
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) header-replace 110907 110905

[Body Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) 110907 110905

[MITM]
h2 = true
hostname = *.island.is, island.is
