[General]

[Rule]
FINAL,DIRECT

[Header Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) header-replace-regex 150109 150109 150106
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) header-replace 150109 150106

[Body Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) 150109 150106

[MITM]
h2 = true
hostname = *.island.is, island.is
