[General]

[Rule]
FINAL,DIRECT

[Header Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) header-replace-regex 051107 051107 051105
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) header-replace 051107 051105

[Body Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) 051107 051105

[MITM]
h2 = true
hostname = *.island.is, island.is
