[General]

[Rule]
FINAL,DIRECT

[Header Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) header-replace-regex 290507 290507 290506
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) header-replace 290507 290506

[Body Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) 290507 290506

[MITM]
h2 = true
hostname = *.island.is, island.is
